# Generated by Django 5.1.2 on 2025-01-26 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("korean", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sense",
            old_name="word_ref",
            new_name="headword_ref",
        ),
    ]
