import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { PersistentDictionaryPageStateContextProvider } from "./web-contexts/PersistentDictionaryPageStateContext";
import { CachingContextProvider } from "@repo/shared/contexts/CachingContextProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <CachingContextProvider cacheCapacity={5}>
          <PersistentDictionaryPageStateContextProvider>
            {children}
          </PersistentDictionaryPageStateContextProvider>
        </CachingContextProvider>
      </body>
    </html>
  );
}
