# Generated by Django 5.1.2 on 2024-10-22 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HanjaCharacter',
            fields=[
                ('character', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('meaning_reading', models.CharField()),
                ('decomposition', models.CharField(null=True)),
                ('radical', models.CharField(null=True)),
                ('radical_source', models.CharField(null=True)),
                ('strokes', models.SmallIntegerField(default=None, null=True)),
                ('grade_level', models.CharField()),
                ('exam_level', models.CharField()),
                ('result_ranking', models.SmallIntegerField(default=-1)),
                ('explanation', models.CharField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KoreanWord',
            fields=[
                ('target_code', models.IntegerField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100, null=True)),
                ('word_type', models.CharField(max_length=3, null=True)),
                ('history_info', models.JSONField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sense',
            fields=[
                ('target_code', models.IntegerField(primary_key=True, serialize=False)),
                ('definition', models.CharField(max_length=1500)),
                ('type', models.CharField(max_length=3, null=True)),
                ('order', models.SmallIntegerField()),
                ('category', models.CharField(max_length=6, null=True)),
                ('pos', models.CharField(max_length=6, null=True)),
                ('additional_info', models.JSONField(default=None, null=True)),
                ('referent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senses', to='words.koreanword')),
            ],
        ),
    ]
