# Generated by Django 5.1.2 on 2024-10-23 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HanjaMeaningReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField()),
                ('reading', models.CharField(max_length=1)),
                ('referent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meaning_readings', to='words.hanjacharacter')),
            ],
        ),
    ]
