# Generated by Django 5.1.2 on 2024-10-24 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_remove_hanjacharacter_meaning_reading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hanjameaningreading',
            name='readings',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
