# Generated by Django 5.1.2 on 2025-01-20 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0006_alter_hanjameaningreading_readings"),
    ]

    operations = [
        migrations.CreateModel(
            name="SenseExample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("example", models.CharField()),
                ("source", models.CharField(null=True)),
                ("translation", models.CharField(null=True)),
                ("origin", models.CharField(null=True)),
                ("region", models.CharField(null=True)),
                (
                    "related_sense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examples",
                        to="words.sense",
                    ),
                ),
            ],
        ),
    ]
