# Generated by Django 5.1.2 on 2025-01-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0007_senseexample"),
    ]

    operations = [
        migrations.AlterField(
            model_name="koreanword",
            name="word",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name="koreanword",
            index=models.Index(fields=["word"], name="index_korean_word_word"),
        ),
    ]
