# Generated by Django 5.1.2 on 2025-01-25 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HanjaCharacter",
            fields=[
                (
                    "character",
                    models.CharField(max_length=1, primary_key=True, serialize=False),
                ),
                ("decomposition", models.CharField(null=True)),
                ("radical", models.CharField(null=True)),
                ("radical_source", models.CharField(null=True)),
                ("strokes", models.SmallIntegerField(default=None, null=True)),
                ("grade_level", models.CharField()),
                ("exam_level", models.CharField()),
                ("result_ranking", models.SmallIntegerField(default=-1)),
                ("explanation", models.CharField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="HanjaMeaningReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meaning", models.CharField(max_length=100)),
                ("readings", models.CharField(max_length=3, null=True)),
                (
                    "referent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meaning_readings",
                        to="hanja.hanjacharacter",
                    ),
                ),
            ],
        ),
    ]
