# Generated by Django 5.1.2 on 2025-01-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "nlp",
            "0002_rename_end_index_in_source_text_derivedexamplelemma_eojeol_number_in_source_text_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SkippedLemma",
            fields=[
                (
                    "word",
                    models.TextField(primary_key=True, serialize=False, unique=True),
                ),
            ],
        ),
    ]
