# Generated by Django 5.1.2 on 2025-01-19 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nlp", "0003_skippedlemma"),
    ]

    operations = [
        migrations.RenameField(
            model_name="skippedlemma",
            old_name="word",
            new_name="lemma",
        ),
    ]
