# Generated by Django 5.1.2 on 2025-01-23 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nlp", "0004_rename_word_skippedlemma_lemma"),
        ("words", "0009_koreanword_result_ranking"),
    ]

    operations = [
        migrations.RenameField(
            model_name="derivedexampletext",
            old_name="user_that_added",
            new_name="user_ref",
        ),
        migrations.AlterField(
            model_name="derivedexamplelemma",
            name="word_ref",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="derived_example_lemmas",
                to="words.koreanword",
            ),
        ),
    ]
