# Generated by Django 5.1.2 on 2025-01-24 16:33

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nlp", "0005_rename_user_that_added_derivedexampletext_user_ref_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="derivedexampletext",
            name="image",
            field=models.ImageField(null=True, upload_to=users.models.get_image_path),
        ),
        migrations.AddField(
            model_name="derivedexampletext",
            name="remote_image_url",
            field=models.URLField(null=True),
        ),
    ]
