# Generated by Django 5.1.2 on 2025-01-24 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nlp", "0006_derivedexampletext_image_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SkippedLemma",
        ),
        migrations.RenameField(
            model_name="derivedexampletext",
            old_name="image",
            new_name="nonremote_image_url",
        ),
    ]
