# Generated by Django 5.1.2 on 2025-01-25 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nlp", "0007_delete_skippedlemma_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="derivedexampletext",
            name="user_ref",
        ),
        migrations.DeleteModel(
            name="DerivedExampleLemma",
        ),
        migrations.DeleteModel(
            name="DerivedExampleText",
        ),
    ]
