# Generated by Django 5.1.2 on 2025-01-25 19:44

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("korean", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DerivedExampleText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("source", models.CharField()),
                (
                    "nonremote_image_url",
                    models.ImageField(null=True, upload_to=users.models.get_image_path),
                ),
                ("remote_image_url", models.URLField(null=True)),
                (
                    "user_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="derived_example_texts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DerivedExampleLemma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lemma", models.CharField()),
                ("eojeol_number_in_source_text", models.IntegerField()),
                (
                    "word_ref",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="derived_example_lemmas",
                        to="korean.koreanheadword",
                    ),
                ),
                (
                    "source_text",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="derived_example_lemmas",
                        to="user_examples.derivedexampletext",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserExampleSentence",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("sentence", models.CharField(max_length=1000)),
                ("source", models.CharField(max_length=1000)),
                (
                    "user_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="added_sentences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "word_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_sentences",
                        to="korean.koreanheadword",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserVideoExample",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("video_id", models.CharField()),
                ("start", models.IntegerField()),
                ("end", models.IntegerField()),
                ("video_text", models.CharField(null=True)),
                ("source", models.CharField(max_length=1000)),
                (
                    "user_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="added_videos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "word_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_videos",
                        to="korean.koreanheadword",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserImage",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("image_accompanying_text", models.CharField(null=True)),
                (
                    "nonremote_image_url",
                    models.ImageField(null=True, upload_to=users.models.get_image_path),
                ),
                ("remote_image_url", models.URLField(null=True)),
                ("source", models.CharField(max_length=1000)),
                (
                    "user_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="added_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "word_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_images",
                        to="korean.koreanheadword",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("remote_image_url__isnull", False),
                            ("nonremote_image_url__isnull", False),
                            _connector="OR",
                        ),
                        name="at_least_one_image_url",
                    )
                ],
            },
        ),
    ]
