# Generated by Django 5.1.2 on 2025-01-26 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_examples", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="derivedexamplelemma",
            old_name="word_ref",
            new_name="headword_ref",
        ),
        migrations.RenameField(
            model_name="userexamplesentence",
            old_name="word_ref",
            new_name="headword_ref",
        ),
        migrations.RenameField(
            model_name="userimage",
            old_name="word_ref",
            new_name="headword_ref",
        ),
        migrations.RenameField(
            model_name="uservideoexample",
            old_name="word_ref",
            new_name="headword_ref",
        ),
    ]
