# Generated by Django 5.1.2 on 2025-02-26 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "user_examples",
            "0002_rename_word_ref_derivedexamplelemma_headword_ref_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="uservideoexample",
            name="video_text",
            field=models.CharField(blank=True, default=""),
        ),
    ]
