# Generated by Django 5.1.2 on 2025-02-27 23:23

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_examples", "0003_alter_uservideoexample_video_text"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userimage",
            name="at_least_one_image_url",
        ),
        migrations.RenameField(
            model_name="derivedexampletext",
            old_name="nonremote_image_url",
            new_name="image_url",
        ),
        migrations.RemoveField(
            model_name="derivedexampletext",
            name="remote_image_url",
        ),
        migrations.RemoveField(
            model_name="userimage",
            name="nonremote_image_url",
        ),
        migrations.RemoveField(
            model_name="userimage",
            name="remote_image_url",
        ),
        migrations.AddField(
            model_name="userimage",
            name="image_url",
            field=models.ImageField(
                default=None, upload_to=users.models.get_image_path
            ),
            preserve_default=False,
        ),
    ]
