# Generated by Django 5.1.2 on 2025-02-27 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_examples", "0004_remove_userimage_at_least_one_image_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userimage",
            name="image_accompanying_text",
            field=models.CharField(blank=True, default=""),
        ),
    ]
