# Generated by Django 5.1.2 on 2024-10-22 12:32

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('known_hanja', models.ManyToManyField(related_name='users_that_know', to='words.hanjacharacter')),
                ('known_words', models.ManyToManyField(related_name='users_that_know', to='words.koreanword')),
                ('studied_hanja', models.ManyToManyField(related_name='users_that_study', to='words.hanjacharacter')),
                ('studied_words', models.ManyToManyField(related_name='users_that_study', to='words.koreanword')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserExampleSentence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order', models.SmallIntegerField()),
                ('sentence', models.CharField(max_length=1000)),
                ('source', models.CharField(max_length=1000, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_examples', to=settings.AUTH_USER_MODEL)),
                ('word_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sentences', to='words.koreanword')),
            ],
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order', models.SmallIntegerField()),
                ('note_text', models.CharField(max_length=100, null=True)),
                ('note_image', models.ImageField(upload_to=users.models.get_image_path)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_notes', to=settings.AUTH_USER_MODEL)),
                ('word_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notes', to='words.koreanword')),
            ],
        ),
    ]
