# Generated by Django 5.1.2 on 2025-01-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_image_userimage_image_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uservideoexample",
            old_name="time",
            new_name="end",
        ),
        migrations.RemoveField(
            model_name="uservideoexample",
            name="video_url",
        ),
        migrations.AddField(
            model_name="uservideoexample",
            name="start",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="uservideoexample",
            name="video_id",
            field=models.CharField(default=""),
            preserve_default=False,
        ),
    ]
