# Generated by Django 5.1.2 on 2025-01-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_rename_time_uservideoexample_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uservideoexample",
            name="end",
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="uservideoexample",
            name="start",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
