# Generated by Django 5.1.2 on 2025-01-24 16:46

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_uservideoexample_end_and_more"),
        ("words", "0009_koreanword_result_ranking"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userimage",
            name="image_url",
        ),
        migrations.AddField(
            model_name="userimage",
            name="nonremote_image_url",
            field=models.ImageField(null=True, upload_to=users.models.get_image_path),
        ),
        migrations.AddField(
            model_name="userimage",
            name="remote_image_url",
            field=models.URLField(null=True),
        ),
        migrations.AddConstraint(
            model_name="userimage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("remote_image_url__isnull", False),
                    ("nonremote_image_url__isnull", False),
                    _connector="OR",
                ),
                name="at_least_one_image_url",
            ),
        ),
    ]
