# Generated by Django 5.1.2 on 2025-01-25 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_userimage_image_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userimage",
            name="user_ref",
        ),
        migrations.RemoveField(
            model_name="userimage",
            name="word_ref",
        ),
        migrations.RemoveField(
            model_name="uservideoexample",
            name="user_ref",
        ),
        migrations.RemoveField(
            model_name="uservideoexample",
            name="word_ref",
        ),
        migrations.DeleteModel(
            name="UserExampleSentence",
        ),
        migrations.DeleteModel(
            name="UserImage",
        ),
        migrations.DeleteModel(
            name="UserVideoExample",
        ),
    ]
